FROM hansd/base:14.04
MAINTAINER Hans Donner <hans.donner@pobox.com> "https://github.com/hans-d"

$IMPORT common/default-layout.docker

RUN apt-get -y install postfix

$IMPORT common/supervisor.docker

$IMPORT common/add-scripts.docker
$IMPORT common/add-templates.docker

$IMPORT common/default-entrypoint.docker

EXPOSE 25
