# Autogenerated - do not edit
FROM hansd/base:latest
MAINTAINER Hans Donner <hans.donner@pobox.com> "https://github.com/hans-d"

RUN apt-get -y install postfix && \
    rm /etc/postfix/*.cf && \
    cp /etc/services /var/spool/postfix/etc/.

RUN mkdir -p /docker/scripts /docker/templates
ADD common/scripts /docker/scripts

ADD templates /docker/templates

ADD etc /etc

RUN chmod +x --recursive /etc/my_init.d/* /etc/service/*

RUN rm -rf /etc/service/sshd /etc/my_init.d/00_regen_ssh_host_keys.sh

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


EXPOSE 25
