FROM hansd/base:latest
MAINTAINER Hans Donner <hans.donner@pobox.com> "https://github.com/hans-d"

RUN apt-get -y install postfix && \
    rm /etc/postfix/*.cf && \
    cp /etc/services /var/spool/postfix/etc/.

$IMPORT common/default-layout.docker
$IMPORT common/add-templates.docker
$IMPORT common/add-etc.docker
$IMPORT common/executable-init.docker
$IMPORT common/disable-ssh.docker
$IMPORT common/clean-apt.docker

EXPOSE 25
