.phony: git-sub build clean

TAGNAME = test-postfix

Dockerfile: Dockerfile.docker common/*.docker
	@echo Generate Dockerfile
	@cp Dockerfile.docker Dockerfile
	@perl -pe 's/\$$IMPORT (.*)/`test -f $$1 && cat $$1`/ge' -i Dockerfile
	@sed '1s/^/\# Autogenerated - do not edit\n/' -i Dockerfile

build: Dockerfile
	docker build --tag $(TAGNAME) . 

clean:
	rm Dockerfile

git-sub:
	git submodule init
	git submodule update
