#!/bin/bash
set -e

. /docker/scripts/functions

status "Init postfix" 

POSTFIX_SSL_CERT=${POSTFIX_SSL_CERT:-/etc/ssl/certs/ssl-cert-snakeoil.pem}
POSTFIX_SSL_KEY=${POSTFIX_SSL_KEY:-/etc/ssl/private/ssl-cert-snakeoil.key}
POSTFIX_SSL=${POSTFIX_SSL:-true}

POSTFIX_HOSTNAME=${POSTFIX_HOSTNAME:-123}
ALIAS_MAPS=${ALIAS_MAPS:-hash:/etc/aliases}
ALIAS_DB=${ALIAS_DB:-hash:/etc/aliases}
POSTFIX_DESTINATION=${POSTFIX_DESTINATION:-}
POSTFIX_RELAY_HOSTS=${POSTFIX_RELAY_HOSTS:-}
POSTFIX_NETWORKS=${POSTFIX_NETWORKS:-127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128}

POSTFIX_CFG=${POSTFIX_CFG:-/etc/postfix}

status "configure templates"
copy_template_if_not_present "postfix" "/etc/postfix"

update_template , POSTFIX_SSL_CERT "${POSTFIX_SSL_CERT}" /etc/postfix/main.cf
update_template , POSTFIX_SSL_KEY "${POSTFIX_SSL_KEY}" /etc/postfix/main.cf
update_template / POSTFIX_SSL "${POSTFIX_SSL}" /etc/postfix/main.cf
update_template / POSTFIX_HOSTNAME "${POSTFIX_HOSTNAME}" /etc/postfix/main.cf
update_template , ALIAS_MAPS "${ALIAS_MAPS}" /etc/postfix/main.cf
update_template , ALIAS_DB "${ALIAS_DB}" /etc/postfix/main.cf
update_template / POSTFIX_DESTINATION "${POSTFIX_DESTINATION}" /etc/postfix/main.cf
update_template ; POSTFIX_RELAY_HOSTS "${POSTFIX_RELAY_HOSTS}" /etc/postfix/main.cf
update_template / POSTFIX_NETWORKS "${POSTFIX_NETWORKS}" /etc/postfix/main.cf

update_template ; POSTFIX_CFG "${POSTFIX_CFG}" /etc/supervisor/conf.d/postfix.conf
